fix error handling
Signed-off-by: Takumi Yanagawa <yana@jp.ibm.com>

diff --git a/.github/workflows/agent_registration.yaml b/.github/workflows/agent_registration.yaml
--- a/.github/workflows/agent_registration.yaml
+++ b/.github/workflows/agent_registration.yaml
@@ -118,32 +118,42 @@ jobs:
           agent_body=$(echo $response_json | jq '{"name": ."Agent Name", "type" : ."Agent Type", "level" : ."Agent Level", "scenario_categories" : [."Agent Scenarios" | to_entries[] | select(.value).key]}')
           
           echo $agent_body | jq
-
-          reg_resp=$(curl \
+          
+          response_file=$(mktemp)
+          trap 'echo "Cleaning up $response_file"; rm -f "$response_file"' EXIT
+          status_code=$(curl \
             --url ${{vars.ITBENCH_API}}/gitops/agents?github_username=${{ github.event.issue.user.login }} \
             --header "authorization: Bearer ${{ secrets.ITBENCH_API_TOKEN }}" \
             --header 'content-type: application/json' \
-            --data "$agent_body")
+            --data "$agent_body" \
+            --output "$response_file" \
+            --write-out "%{http_code}")
 
           if [[ $? -eq 0 ]]; then
           
-            echo "Request was successful"
+            echo "Curl execution was successful"
 
             # Check that the spec is in the response body
           
-            if [[ $? -eq 0 ]]; then
+            if [[ "$status_code" == "200" || "$status_code" == "201" ]]; then
+              
+              echo "manifest=$( cat $response_file | jq '.spec.agent_manifest + {metadata: {id: .metadata.id}}' | base64 -w 0)" >> "$GITHUB_OUTPUT"
 
-              echo "manifest=$( echo $reg_resp | jq '.spec.agent_manifest + {metadata: {id: .metadata.id}}' | base64 -w 0)" >> "$GITHUB_OUTPUT"
-             
             else
-              echo "Body recieved from IT bench was invalid."
-              echo $reg_resp
+              msg="Body recieved from IT bench was invalid."
+              echo "$msg"
+              echo "error=1" >> "$GITHUB_OUTPUT"
+              error_detail=$(jq -r '.detail // "No detail message in response."' "$response_file")
+              echo "error_detail=${error_detail}" >> "$GITHUB_OUTPUT"
               exit 1
             fi
 
           else
             echo "Request failed."
-            echo $reg_resp
+            msg="CURL execution was failed with status code $status_code."
+            echo "$msg"
+            echo "error=1" >> "$GITHUB_OUTPUT"
+            echo "error_detail=$msg" >> "$GITHUB_OUTPUT"
             exit 1
           fi
 
@@ -221,6 +231,7 @@ jobs:
         uses: actions/github-script@v7
         env:
           PRIVATE_REPO:  ${{ steps.check-repo-private.outputs.error_public_repo == 1}}
+          ERROR_ON_GENERATE_MANIFEST: ${{ steps.generate-manifest.outputs.error == 1 }}
           COMMENT_BODY: |
             👋 ${{ github.event.issue.user.login }}
 
@@ -243,6 +254,18 @@ jobs:
             ----
 
             Run link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+
+          ERROR_ON_GENERATE_MANIFEST_COMMENT_BODY: |
+            👋 ${{ github.event.issue.user.login }}
+        
+            There was an issue while registering the agent.
+        
+            Error Detail:
+            ${{ steps.generate-manifest.outputs.error_detail }}
+        
+            ----
+        
+            Run link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
         
         with:
           script: |
@@ -255,6 +278,14 @@ jobs:
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 body: process.env.PRIV_REPO_COMMENT_BODY
+              })
+            } else if (process.env.ERROR_ON_GENERATE_MANIFEST == 'true') {
+               console.log("Responding with manifest error message.")
+               github.rest.issues.createComment({
+                issue_number: context.issue.number,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                body: process.env.ERROR_ON_GENERATE_MANIFEST_COMMENT_BODY
               })
             } else {
               console.log("Responding with generic error message.")
